---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: {{.Values.letsencrypt.server}}
    email: {{.Values.letsencrypt.email}}
    privateKeySecretRef:
      name: letsencrypt-private-key
    http01: {}
